New UI
mitre/debrief pull request #53
Opened 2021-10-27 15:17 UTC by argaudreau

## Description

This PR updates debrief to use the new UI (Alpine and Bulma) and fixes any bugs associated with that transition. jQuery is no longer a dependency in this plugin.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

All buttons and functions were tested in Firefox and Chrome to ensure there were no console errors or UI bugs.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-11-06 06:00 UTC, iguannalin submitted a review, later dismissed

2021-11-08 18:42 UTC, mchan143 requested changes
Everything seems to be working for the most part but I'm seeing a minor issue with closing the debrief tab and reopening (without refreshing the page) resulting in a `SyntaxError: Can't create duplicate variable: 'GRAPH_IMAGE_URLS'` error. Because the debrief list of operations doesn't update automatically, my work flow was to close the debrief tab and re-open to pull any newly run operations.

Any chance more space can go to enlarging the graph? It seems a bit small and cramped on the right hand side with the legend taking up practically a third of the graph view.

2021-11-12 14:38 UTC, argaudreau commented
> Everything seems to be working for the most part but I'm seeing a minor issue with closing the debrief tab and reopening (without refreshing the page) resulting in a `SyntaxError: Can't create duplicate variable: 'GRAPH_IMAGE_URLS'` error. Because the debrief list of operations doesn't update automatically, my work flow was to close the debrief tab and re-open to pull any newly run operations.
> 
> Any chance more space can go to enlarging the graph? It seems a bit small and cramped on the right hand side with the legend taking up practically a third of the graph view.

The graph is now resizable, variable redeclaration errors are gone when you reopen debrief, and the operations list auto updates every 3 seconds so you don't have to reload the page.

2021-11-12 21:43 UTC, mchan143 approved these changes
LGTM

2021-11-16 13:58 UTC, merged